apiVersion: apps/v1
kind: Deployment
metadata:
  name: cropdroid
spec:
  template:
    spec:
      imagePullSecrets:
      containers:
      - name: cropdroid
        #image: localhost:5000/cropdroid-cluster-ubuntu:latest