ARG BASE_IMAGE="golang:latest"

FROM $BASE_IMAGE

LABEL maintainer="jeremyhahn <mail@jeremyhahn.com>"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        build-essential \
        git

WORKDIR /cropdroid
COPY src/go-cropdroid/ .

RUN go get
