FROM alpine:latest

LABEL maintainer="jeremyhahn <mail@jeremyhahn.com>"

WORKDIR /cropdroid
COPY . .

RUN apk update
RUN apk add --update --no-cache \
    build-base \
    linux-headers \
    cmake \
    bash \
    perl \
    git \
    go
