FROM alpine:latest

LABEL maintainer="jeremyhahn <mail@jeremyhahn.com>"

ARG CORES=20
ARG ROCKSDB_VERSION=v6.10.2

ENV CORES=${CORES} ROCKSDB_VERSION=${ROCKSDB_VERSION}

RUN apk update
RUN apk add --update --no-cache \
    snappy-dev \
    zlib-dev \
    bzip2-dev \
    lz4-dev

RUN cd /tmp && \
    git clone https://github.com/gflags/gflags.git && \
    cd gflags && \
    mkdir build && \
    cd build && \
    cmake -DBUILD_SHARED_LIBS=1 -DGFLAGS_INSTALL_SHARED_LIBS=1 .. && \
    make install && \
    cd /tmp && \
    rm -R /tmp/gflags/

RUN cd /tmp && \
    git clone https://github.com/facebook/rocksdb.git && \
    cd rocksdb && \
    git checkout $ROCKSDB_VERSION && \
    make -j$CORES static_lib

#RUN cd /tmp/rocksdb && \
#    make install-static
