ARG BASE_IMAGE=ubuntu:latest
ARG STANDALONE_BUILDER=builder-cropdroid-standalone-ubuntu

FROM $STANDALONE_BUILDER as standalone_builder

FROM $BASE_IMAGE

ARG TIMEZONE=Eastern
ARG CROPDROID_SRC=src/go-cropdroid/
ARG CROPDROID_HOME=/opt/cropdroid
ARG CROPDROID_USER=www-data
ARG LIB_DIR=/usr/local/lib

ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8

RUN DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        locales \
        tzdata && \
        rm -rf /var/lib/apt/lists/*

RUN ln -fs /usr/share/zoneinfo/US/${TIMEZONE} /etc/localtime && dpkg-reconfigure -f noninteractive tzdata

WORKDIR $CROPDROID_HOME
COPY $CROPDROID_SRC/public_html/ $CROPDROID_HOME/public_html
COPY $CROPDROID_SRC/keys $CROPDROID_HOME/keys
COPY --from=standalone_builder /cropdroid/cropdroid $CROPDROID_HOME/cropdroid

RUN chmod 777 -R $CROPDROID_HOME/public_html && \
    mkdir -p $CROPDROID_HOME/db && \
    chmod 777 -R $CROPDROID_HOME/db && \
    touch /var/log/cropdroid.log && \
    chmod 777 /var/log/cropdroid.log && \
    ln -s /opt/cropdroid/cropdroid /usr/local/bin/cropdroid

CMD ["cropdroid", "standalone", "--debug", "--ssl=false", "--enable-registrations"]