ARG BASE_IMAGE=builder-cropdroid-base-ubuntu
ARG ROCKSDB_IMAGE=builder-rocksdb-ubuntu
ARG CORES=2

FROM $BASE_IMAGE

ARG CORES
ENV CORES=${CORES}

RUN apt-get install -y \
    build-essential \
    git \
    libgflags-dev \
    libsnappy-dev \
    zlib1g-dev \
    libbz2-dev \
    libzstd-dev \
    liblz4-dev  \
    librocksdb-dev

RUN make -j${CORES} gorocksdb build-cluster-rocksdb-debug-static
