ARG BASE_IMAGE=builder-cropdroid-base-ubuntu
ARG ROCKSDB_IMAGE=builder-rocksdb-ubuntu
ARG CORES=2

FROM $ROCKSDB_IMAGE

FROM $BASE_IMAGE

ARG CORES
ENV CORES=${CORES}

WORKDIR /cropdroid

#COPY . .
#RUN apt-get update && \
#    apt-get upgrade -y && \
#    apt-get install -y \
#        build-essential \
#        git

RUN apt-get install -y \
    libgflags-dev \
    libsnappy-dev \
    zlib1g-dev \
    libbz2-dev \
    libzstd-dev \
    liblz4-dev

COPY --from=0 /rocksdb /rocksdb
COPY --from=0 /usr/local/lib/librocksdb.a /usr/local/lib/

RUN ROCKSDB_HOME=/rocksdb make gorocksdb
RUN make get-deps
RUN ROCKSDB_HOME=/rocksdb make build-cluster-rocksdb-debug-static

#RUN ROCKSDB_HOME=/rocksdb make -j${CORES} gorocksdb build-cluster-rocksdb-debug-static
#GO111MODULE=auto ROCKSDB_HOME=/rocksdb make gorocksdb build-cluster-rocksdb-debug-static
#ROCKSDB_HOME=/rocksdb make get-deps gorocksdb build-cluster-rocksdb-debug-static
#ROCKSDB_HOME=/rocksdb make gorocksdb build-cluster-rocksdb-debug-static
#CGO_CFLAGS="-I/rocksdb/include" CGO_LDFLAGS="-L/rocksdb -lrocksdb -lstdc++ -lm -lz -lbz2 -lsnappy -llz4 -lzstd -ldl" GOOS=linux go get github.com/tecbot/gorocksdb
